services:
  web:
    build:
      context: ./app
    container_name: fastapi_app
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
